### ISSUE TITLE
** (UndefinedFunctionError) undefined function: String.to_char_list!/1

### ISSUE THREAD

**Issue by b0oh** [meh/httprot#5]
If I do
```
> HTTProt.get("https://github.com/meh/httprot")
```
I get
```
** (UndefinedFunctionError) undefined function: String.to_char_list!/1
     (elixir) String.to_char_list!("github.com")
     (socket) lib/socket/ssl.ex:134: Socket.SSL.connect/3
    (httprot) lib/httprot/request.ex:42: HTTProt.Request.open/3
    (httprot) lib/httprot.ex:20: HTTProt.get/2
```
It is not really httprot problem but socket, can be easily fixed with `{:socket, github: "meh/elixir-socket", tag: "ec03c935565dbe4708d6b594ef57d6de17a93592", override: true}` in mix.exs where tag is current master hash, so probably it is a time just to make new release of socket.

**Comment by meh** [comment]
I did release with the last issue fix, just `mix deps.update`! :panda_face:

**Comment by b0oh** [comment]
yey!

**Comment by b0oh** [comment]
Problem still exists. Probably I wasn't clear, problem is that the latest release of https://github.com/meh/elixir-socket doesn't work, it contains `String.to_char_list!/1` which is not in stdlib anymore, but it fixed in master, what I meant it is to make a 0.2.9 release of socket package.

**Comment by meh** [comment]
You were clear, it's just the heat takes its toll on my brain, releasing that one as well.

**Comment by meh** [comment]
Released a new version, but it's `0.3.0` because there was a minor API change *(it shouldn't affect anyone tho, but better safe than sorry)*.

**Comment by b0oh** [comment]
So, should I explicitly use socket with override: true, or a new version of httprot with fixed dependencies coming as well?

**Comment by meh** [comment]
Just pushed that one as well :)

**Comment by b0oh** [comment]
Perfect!
